### ISSUE TITLE
Players being teleported on top of water

### ISSUE THREAD

**Issue by Gnoarn** [AcmeProject/WildernessTp#25]
Paper version git-Paper-355
wildernesstp 2.1

ok should add in a check for block being water underneath player.
have not looked completely through the code yet. but its what i would do with it. 
check that the block player would be on top of being water.
this was also happening with the latest version of spigot as well.

also here is some of the biomes
that i was teleported to during testing
- DEEP_FROZEN_OCEAN
- COLD_OCEAN
- LUKEWARM_OCEAN
- RIVER
- DEEP_LUKEWARM_OCEAN
- WARM_OCEAN
- DEEP_WARM_OCEAN

**Comment by RoboMWM** [comment]
These biomes are added to the biome blacklist by default.

We don't do a water check since we assume that water is safe, and with those biomes blacklisted, land is assumed to be nearby. You'll need to either add those biomes yourself or delete the biome blacklist to let the plugin regenerate that section for you.

If it's not doing that or respecting the blacklist feel free to comment here and I'll reopen.

**Comment by Gnoarn** [comment]
the only thing it does is these biomes when doing anything and that is deleting the config file.
- DEEP_OCEAN
- OCEAN
- FROZEN_OCEAN

**Comment by RoboMWM** [comment]
Yea, no idea what's going on with the fileconfiguration object. I'm guessing it's using the default from the included config I guess. Will fix.

**Comment by RoboMWM** [comment]
Whenever it's approved, https://dev.bukkit.org/projects/wildernesstp-the-one-true-wildtp/files/2630595
