### ISSUE TITLE
RTP into blocks

### ISSUE THREAD

**Issue by slvlr** [AcmeProject/WildernessTp#60]
Players are randomly tping into blocks:

https://www.youtube.com/watch?v=iPg4U_Ty6og&feature=emb_logo

Is this a bug or is there a config issue to prevent this please?
Version: 2.14
Minecraft: 1.15.2

**Comment by RoboMWM** [comment]
I heard this was a spigot issue. https://www.spigotmc.org/threads/wilderness-tp.145440/page-28#post-3680233

**Comment by slvlr** [comment]
@RoboMWM This happens on Paper build 93

**Comment by RoboMWM** [comment]
Paper is a fork of spigot, and per that post it started occurring ever since they merged upstream (which is spigot) back on build 90.

**Comment by RoboMWM** [comment]
If someone can figure out what spigot did, then I can resolve this issue.

**Comment by RoboMWM** [comment]
Looks like this guy found out. https://www.spigotmc.org/threads/wilderness-tp.145440/page-28#post-3684333

**Comment by pjt0720** [comment]
I am having the same issue, do you happen to know when you will fix this bug? Not trying to rush into doing anything, but just what to know a time frame since I am telling my server to not use /wild or /rtp for the time being.

Thanks
pjt0720

**Comment by RoboMWM** [comment]
soon™

Probably weekend. Remind me so I don't forget. Or if someone else gets to fixing it, according to what the supposed spigot change was, all I expect is just needing to get the relative block above the initially-retrieved block I guess.

**Comment by RoboMWM** [comment]
alright fixed this alleged spigot change with the next update, I say alleged because I haven't bothered to go through spigot's commit history to see if this actually happened or not. If it did then it surely wasn't announced, at least not on the spigot homepage.

**Comment by RoboMWM** [comment]
So the change was made here https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/807a677e9a59929e27ac1991c3fa1cf6a2ec0f4d

And this was when I made the change back in https://github.com/AcmeProject/WildernessTp/commit/a7dc0afbff386a894c65e3ea828cb0239c3babab

I'm really not sure when the behavior changed to that method though, so I'm not really sure who's really at fault. It very likely may have been that spigot introduced that new bug right about the same time I pulled those giant PRs, so the refactoring in those PRs (which may have removed my extra checks...) probably still "worked" because of the spigot "bug" that was now just resolved...
