### ISSUE TITLE
WildTP Permission Bug

### ISSUE THREAD

**Issue by AccioAce** [AcmeProject/WildernessTp#98]
I was told to open a bug report by RoboMWM about a bug report we have been talking about on Spigot.

I have been using these two permissions: wild.wildtp and wild.wildtp.[world] by that still allow players to bypass it with /rtp or /wild worldname.

I believe the permission: wild.wildtp.[world] is bugged since it doesn't work. It allows players to bypass it by wild teleporting within any worlds using /wild worldname

**Comment by RoboMWM** [comment]
Thanks for the report

As a reminder to mostly myself/others who want to PR, the issue is `wild.wildtp.world.*` is set to default to `true` in plugin.yml when it should default to `op` or `false`. The current workaround is to negate this permission, but negating perms can get messy so it's better to fix this sooner than later.

**Comment by AccioAce** [comment]
ah I see, will you be fixing as dev update or next release update? If is dev where are there dev builds, I'm just curious.

**Comment by RoboMWM** [comment]
fixed and will release shortly
